"""Add genome compression field

Revision ID: 40c711d276f0
Revises: 41c9af002856
Create Date: 2016-05-05 20:55:55.394330

"""

# revision identifiers, used by Alembic.
revision = '40c711d276f0'
down_revision = '41c9af002856'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compression', sa.Enum('gzip'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.drop_column('compression')

    ### end Alembic commands ###
