"""Change up genbank cols, more metadata

Revision ID: 704356629cab
Revises: bced8fa7ef02
Create Date: 2016-04-16 19:44:08.297432

"""

# revision identifiers, used by Alembic.
revision = '704356629cab'
down_revision = 'bced8fa7ef02'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('genome_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.String(), nullable=True))

    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gb_db', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gb_summary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gb_taxid', sa.Integer(), nullable=True))
        batch_op.alter_column('ncbi_gi', new_column_name='gb_id')
        batch_op.alter_column('organism_name', new_column_name='organism')
        batch_op.alter_column('ncbi_acc', new_column_name='gb_acc')
        batch_op.alter_column('assembled', new_column_name='is_assembled')
        batch_op.drop_column('organism_taxonomy')

    with op.batch_alter_table('kmer_collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.String(), nullable=True))

    with op.batch_alter_table('kmer_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra', sa.String(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kmer_sets', schema=None) as batch_op:
        batch_op.drop_column('extra')

    with op.batch_alter_table('kmer_collections', schema=None) as batch_op:
        batch_op.drop_column('extra')

    with op.batch_alter_table('genomes', schema=None) as batch_op:
        batch_op.drop_column('gb_summary')
        batch_op.drop_column('gb_db')
        batch_op.drop_column('gb_taxid')
        batch_op.drop_column('extra')
        batch_op.alter_column('gb_id', new_column_name='ncbi_gi')
        batch_op.alter_column('organism', new_column_name='organism_name')
        batch_op.alter_column('gb_acc', new_column_name='ncbi_acc')
        batch_op.alter_column('is_assembled', new_column_name='assembled')
        batch_op.add_column(sa.Column('organism_taxonomy', sa.String(), nullable=True))

    with op.batch_alter_table('genome_sets', schema=None) as batch_op:
        batch_op.drop_column('extra')

    ### end Alembic commands ###
