"""Initial revision

Revision ID: bced8fa7ef02
Revises: 
Create Date: 2016-04-17 19:50:44.417190

"""

# revision identifiers, used by Alembic.
revision = 'bced8fa7ef02'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genome_sets',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('genomes',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('ncbi_gi', sa.Integer(), nullable=True),
    sa.Column('ncbi_acc', sa.Integer(), nullable=True),
    sa.Column('assembled', sa.Boolean(), nullable=False),
    sa.Column('organism_name', sa.String(), nullable=True),
    sa.Column('organism_taxonomy', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_format', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('ncbi_acc'),
    sa.UniqueConstraint('ncbi_gi')
    )
    op.create_table('kmer_collections',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('directory', sa.String(), nullable=False),
    sa.Column('prefix', sa.String(), nullable=False),
    sa.Column('k', sa.Integer(), nullable=False),
    sa.Column('parameters', wgskmers.database.sqla.JsonType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('directory'),
    sa.UniqueConstraint('title')
    )
    op.create_table('genome_set_assoc',
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['genome_sets.id'], ),
    sa.PrimaryKeyConstraint('set_id', 'genome_id')
    )
    op.create_table('kmer_sets',
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('genome_id', sa.Integer(), nullable=False),
    sa.Column('dtype_str', sa.String(), nullable=False),
    sa.Column('has_counts', sa.Boolean(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['kmer_collections.id'], ),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'genome_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kmer_sets')
    op.drop_table('genome_set_assoc')
    op.drop_table('kmer_collections')
    op.drop_table('genomes')
    op.drop_table('genome_sets')
    ### end Alembic commands ###
